version: '3.5'
# must inform user to set up their cluster docker compose like below:
networks:
  1broker:
    driver: bridge
    name: 1broker

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    networks:
    - 1broker
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
      EXTRA_ARGS: -javaagent:/demo-cluster/configs/jmx-exporter/jmx_prometheus_javaagent-0.19.0.jar=8081:/demo-cluster/configs/jmx-exporter/zookeeper.yml
      KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
    volumes:
      - ./demo-cluster/configs/jmx-exporter:/demo-cluster/configs/jmx-exporter
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1
    networks:
    - 1broker
    ports:
      - '9091:9091'
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9091,INTERNAL://kafka1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_OPTS: -javaagent:/demo-cluster/configs/jmx-exporter/jmx_prometheus_javaagent-0.19.0.jar=8081:/demo-cluster/configs/jmx-exporter/kafka.yml
      KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
    volumes:
      - ./demo-cluster/configs/jmx-exporter:/demo-cluster/configs/jmx-exporter
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9091"]
      interval: 10s
      timeout: 10s
      retries: 5